name: Build and test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt install ninja-build
    - name: CMake
      run: mkdir build && cd build && cmake -GNinja ..
    - name: Build
      run: cmake --build build
    - name: Test
      run: cd build && ctest --output-on-failure
    - name: hello-gcc
      run: cd tests/hello-gcc && ./test.sh
    - name: hello-g++
      run: cd tests/hello-g++ && ./test.sh
    - name: just-return-gcc 
      run: cd tests/just-return-gcc && ./test.sh
    - name: just-return-g++
      run: cd tests/just-return-g++ && ./test.sh
    - name: simple-lib-gcc
      run: cd tests/simple-lib-gcc && ./test.sh
    - name: simple-lib-g++
      run: cd tests/simple-lib-g++ && ./test.sh
    - name: version-gcc
      run: cd tests/version-gcc && ./test.sh
